spring.application.name=melopost

# Default Profile
spring.profiles.active=dev

# Cassandra Configuration (Default values, can be overridden by profiles)
spring.cassandra.enabled=true
spring.cassandra.keyspace-name=melopost
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042

# Multipart Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
