# Acceptance Configuration
spring.cassandra.keyspace-name=melopost_acc
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
# These should likely be overridden by environment variables in a real ACC environment
spring.cassandra.local-datacenter=${CASSANDRA_DATACENTER:datacenter1}
spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:127.0.0.1}
spring.cassandra.port=${CASSANDRA_PORT:9042}

# Logging
logging.level.com.melomarit.melopost=INFO
